CREATE DATABASE customer_behavior;
USE customer_behavior;

-- Q1. What is the total revenue generated by male vs. female customers?

SELECT gender, SUM(purchase_amount) AS total_revenue
From customers
Group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id, purchase_amount
from customers
where discount_applied = 'Yes' 
AND purchase_amount >= (select AVG(purchase_amount) from customers);

-- Q3. Which are the top 5 products with the highest average review rating?

SELECT item_purchased ,
	round(avg(CAST(review_rating as decimal(10,2))),2) as average_product_rating
    from customers
    group by item_purchased
    order by avg(review_rating) desc
    limit 5;

-- --Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type,
round(avg(purchase_amount),2)
from customers
where shipping_type in ('Standard' , 'Express')
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.-

select subscription_status,
count(customer_id) as total_customers,
round(AVG(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customers
group by subscription_status
order by avg_spend desc , total_revenue desc;

-- Q6. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
-- USING CTE
with customer_segements as(
            select customer_id,
            case
                when previous_purchases = 1 THEN 'NEW'
                when previous_purchases between 2 AND 10 THEN 'Returning'
                ELSE 'Loyal'
            END AS customer_type
        from customers
        )
SELECT customer_type,
       COUNT(*) AS number_of_customers
FROM customer_segments
GROUP BY customer_type;

-- USING SUBQUERY

SELECT customer_type,
       COUNT(*) AS number_of_customers
FROM (
    SELECT customer_id,
           CASE
               WHEN previous_purchases = 1 THEN 'New'
               WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS customer_type
    FROM customers
) AS customer_segments
GROUP BY customer_type;

-- Q7. Which 5 products have the highest --percentage-- of purchases with discounts applied?

SELECT item_purchased,
     ROUND(100.0* SUM(
             CASE
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
                END)/COUNT(*) , 2)
                AS discount
     FROM customers
     GROUP BY item_purchased
     ORDER BY discount DESC
     LIMIT 5;           
    
-- Q8. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customers
GROUP BY age_group 
-- USING ORDER BY TO FIND WHICH AGE GROUP CONTRIBUTES THE MOST
ORDER BY total_revenue DESC;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customers
WHERE previous_purchases > 5
GROUP BY subscription_status;






